In [5]:
line = "三輪車　　　　　　　　　　　　　　　　　11235535567HH5HH6536532123565321/22222242222224222222211211211224"
parts = line.strip().split()
parts = parts[1].split("/")
print(parts)

['11235535567HH5HH6536532123565321', '22222242222224222222211211211224']


In [ ]:

audio_name = os.path.splitext(audio_file)[0]

In [2]:
import numpy
matrix = numpy.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
array = [1, 2, 3]

print(matrix/array)

[[2.         1.5        1.33333333]
 [5.         3.         2.33333333]
 [8.         4.5        3.33333333]]
