In [2]:
line = "三輪車　　　　　　　　　　　　　　　　　11235535567HH5HH6536532123565321/22222242222224222222211211211224"
parts = line.strip().split()
parts1 = parts[1].split("/")[0]
parts2 = list(parts[1].split("/")[1])
print(parts1, parts2)

11235535567HH5HH6536532123565321 ['2', '2', '2', '2', '2', '2', '4', '2', '2', '2', '2', '2', '2', '4', '2', '2', '2', '2', '2', '2', '2', '1', '1', '2', '1', '1', '2', '1', '1', '2', '2', '4']


In [ ]:

audio_name = os.path.splitext(audio_file)[0]

In [2]:
import numpy
matrix = numpy.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
array = [1, 2, 3]

print(matrix/array)

[[2.         1.5        1.33333333]
 [5.         3.         2.33333333]
 [8.         4.5        3.33333333]]


In [1]:
import pandas as pd
import os

filepath = r"C:\Users\mrjac\Desktop\丁建均老師信號處理專題\QBH_project\HMM_midi_diff\一千年以後.csv"

print(pd.read_csv(filepath, index_col=0).to_dict())


{'0.001.1': {0.001: 0.001}, '0.001.2': {0.001: 0.0786802030456852}, '0.001.3': {0.001: 0.0788973384030418}, '0.001.4': {0.001: 0.066439863918351}, '0.001.5': {0.001: 0.033226581265012}, '0.001.6': {0.001: 0.0078690189110293}, '0.001.7': {0.001: 0.0006680806365279}, '0.001.8': {0.001: 0.0016445475638051}, '0.001.9': {0.001: 0.0032911232536802}, '0.001.10': {0.001: 0.0016445475638051}, '0.001.11': {0.001: 0.0006160034733689}, '0.001.12': {0.001: 0.001}, '0.001.13': {0.001: 0.001}, '0.001.14': {0.001: 0.001}, '0.001.15': {0.001: 0.001}, '0.001.16': {0.001: 0.001}, '0.001.17': {0.001: 0.001}, '0.001.18': {0.001: 0.001}, '0.001.19': {0.001: 0.001}, '0.001.20': {0.001: 0.001}, '0.001.21': {0.001: 0.001}, '0.001.22': {0.001: 0.001}}


In [2]:
import numpy as np

# 讀取 CSV 並轉換為 NumPy 矩陣
file_path = r"C:\Users\mrjac\Desktop\丁建均老師信號處理專題\QBH_project\HMM_midi_diff\一千年以後.csv"
matrix = np.loadtxt(file_path, delimiter=",")
print(matrix)

[[1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03]
 [1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03]
 [1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03 1.00000000e-03
  1.00000000e-03 1.00000000e-03 1.00000000e-03 2.14206443e-04
  5.73388554e-04 1.14677711e-03 5.73388554e-04 2.32510172e-04
  1.00000000e-03 1.00000000e-03 1.00